server:
  error:
    include-stacktrace: always
  port: 8080
  servlet:
    context-path: /

spring:
  profiles:
    active: desk

  application:
    name: skeleton_elasticsearch

elasticsearch:
  host: 192.168.136.128
  port: 5601
  cluster: elasticsearch


---
spring:
  profiles: local

---
spring:
  profiles: desk