server:
  error:
    include-stacktrace: always
  port: 8080
  servlet:
    context-path: /

spring:
  profiles:
    active: local

  application:
    name: skeleton_elasticsearch

elasticsearch:
  host: 192.168.136.128
  port: 9200
  cluster: elasticsearch


---
spring:
  profiles: local

elasticsearch:
  host: 192.168.23.128
  port: 9200
  cluster: elasticsearch

---
spring:
  profiles: desk

elasticsearch:
  host: 192.168.136.128
  port: 9200
  cluster: elasticsearch